module corbaConversion {
    // Définition de l'interface IConversionRemote
    interface IConversionRemote {
        // Déclaration d'une opération de conversion prenant un montant en entrée et retournant un montant converti
        double conversionMontant(in double montant);
    };
};
